/*
 * pack_engine.c - Tool to pack and compress xbootsplash engine sources using ZX0
 */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdint.h>
#include "../../zx0/zx0_compress.h"

static const char *file_list[] = {
    "engine_src/generate_splash.c",
    "engine_src/splash_anim_delta.c",
    "engine_src/splash_anim_drm.c",
    "engine_src/nolibc.h",
    "engine_src/start.S",
    "engine_src/linker.ld",
    "Makefile",
    "zx0/zx0_compress.c",
    "zx0/zx0_compress.h",
    "zx0/zx0_decompress.c",
    "zx0/zx0_decompress.h",
    "upkr/upkr_compress.c",
    "upkr/upkr_compress.h",
    "upkr/upkr_decompress.c",
    "upkr/upkr_decompress.h",
    "icons/resume.png",
    "icons/resume_hd.png",
    NULL
};

static unsigned char *append_data(unsigned char *buf, size_t *cap, size_t *len, const void *data, size_t size) {
    if (*len + size > *cap) {
        size_t new_cap = (*cap == 0) ? 65536 : *cap * 2;
        while (new_cap < *len + size) new_cap *= 2;
        unsigned char *new_buf = (unsigned char *)realloc(buf, new_cap);
        if (!new_buf) {
            fprintf(stderr, "pack_engine: out of memory\n");
            free(buf);
            exit(1);
        }
        buf = new_buf;
        *cap = new_cap;
    }
    memcpy(buf + *len, data, size);
    *len += size;
    return buf;
}

int main(int argc, char **argv) {
    if (argc < 3) {
        fprintf(stderr, "Usage: %s <project_root> <output_header>\n", argv[0]);
        return 1;
    }

    const char *project_root = argv[1];
    const char *output_file = argv[2];

    unsigned char *raw_buf = NULL;
    size_t raw_cap = 0;
    size_t raw_len = 0;

    for (int i = 0; file_list[i]; i++) {
        const char *rel_path = file_list[i];
        char full_path[1024];
        snprintf(full_path, sizeof(full_path), "%s/%s", project_root, rel_path);

        FILE *f = fopen(full_path, "rb");
        if (!f) {
            fprintf(stderr, "pack_engine: error opening source file '%s'\n", full_path);
            free(raw_buf);
            return 1;
        }

        fseek(f, 0, SEEK_END);
        long sz = ftell(f);
        fseek(f, 0, SEEK_SET);

        if (sz < 0) {
            fprintf(stderr, "pack_engine: error getting size of '%s'\n", full_path);
            fclose(f);
            free(raw_buf);
            return 1;
        }

        unsigned char *fbuf = (unsigned char *)malloc((size_t)sz);
        if (!fbuf && sz > 0) {
            fprintf(stderr, "pack_engine: out of memory reading '%s'\n", full_path);
            fclose(f);
            free(raw_buf);
            return 1;
        }

        if (sz > 0 && fread(fbuf, 1, (size_t)sz, f) != (size_t)sz) {
            fprintf(stderr, "pack_engine: error reading '%s'\n", full_path);
            free(fbuf);
            fclose(f);
            free(raw_buf);
            return 1;
        }
        fclose(f);

        uint16_t path_len = (uint16_t)strlen(rel_path);
        uint32_t file_len = (uint32_t)sz;

        raw_buf = append_data(raw_buf, &raw_cap, &raw_len, &path_len, sizeof(path_len));
        raw_buf = append_data(raw_buf, &raw_cap, &raw_len, rel_path, path_len);
        raw_buf = append_data(raw_buf, &raw_cap, &raw_len, &file_len, sizeof(file_len));
        if (sz > 0) {
            raw_buf = append_data(raw_buf, &raw_cap, &raw_len, fbuf, (size_t)sz);
            free(fbuf);
        }
    }

    /* Sentinel end of archive: path_len = 0 */
    uint16_t sentinel = 0;
    raw_buf = append_data(raw_buf, &raw_cap, &raw_len, &sentinel, sizeof(sentinel));

    printf("pack_engine: Uncompressed raw archive size: %zu bytes\n", raw_len);

    unsigned char *comp_buf = NULL;
    size_t comp_len = 0;
    if (zx0_compress_custom(raw_buf, raw_len, &comp_buf, &comp_len, 0) != 0) {
        fprintf(stderr, "pack_engine: ZX0 compression failed\n");
        free(raw_buf);
        return 1;
    }

    printf("pack_engine: ZX0 compressed archive size: %zu bytes (ratio: %.1f%%)\n",
           comp_len, ((double)comp_len / (double)raw_len) * 100.0);

    FILE *out = fopen(output_file, "w");
    if (!out) {
        fprintf(stderr, "pack_engine: error opening output header '%s'\n", output_file);
        free(comp_buf);
        free(raw_buf);
        return 1;
    }

    fprintf(out, "/* Autogenerated by pack_engine - do not edit */\n");
    fprintf(out, "#ifndef EMBEDDED_ENGINE_H\n#define EMBEDDED_ENGINE_H\n\n");
    fprintf(out, "#include <stddef.h>\n\n");
    fprintf(out, "static const size_t embedded_engine_uncompressed_size = %zu;\n", raw_len);
    fprintf(out, "static const size_t embedded_engine_compressed_size = %zu;\n\n", comp_len);
    fprintf(out, "static const unsigned char embedded_engine_zx0[] = {\n");

    for (size_t i = 0; i < comp_len; i++) {
        fprintf(out, "0x%02x%s", comp_buf[i], (i + 1 < comp_len) ? "," : "");
        if ((i + 1) % 16 == 0) fprintf(out, "\n");
    }
    fprintf(out, "\n};\n\n#endif /* EMBEDDED_ENGINE_H */\n");

    fclose(out);
    free(comp_buf);
    free(raw_buf);
    printf("pack_engine: Successfully generated '%s'\n", output_file);
    return 0;
}
