#ifndef XBOOTSPLASH_GUI_VERSION_H
#define XBOOTSPLASH_GUI_VERSION_H

#define XBOOTSPLASH_GUI_NAME    "XBootsplash Studio"
#define XBOOTSPLASH_GUI_VERSION "1.0.0"
#define XBOOTSPLASH_GUI_AUTHOR  "seb3773"

#endif // XBOOTSPLASH_GUI_VERSION_H
